version: "3.1"
services:
  api:
    build: ./api

    volumes:
      - ./api:/code
    command: ./wait-for-it.sh db:5432 -- /usr/local/bin/gunicorn --reload -w 2 -b :8000 books:app
    env_file:
      - postgres.env
    depends_on:
      - db
    restart: always
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static-content:/wwww/static
    depends_on:
      - api
      - db
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - REACT_APP_BOOKS_SERVICE_URL=http://api:8000/
    ports:
      - 3000:3000
      - 35729:35729 # expose WebSocket used for hot reploading
    volumes:
      - ./client:/code
    depends_on:
      - api
  db:
    build: ./db
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - postgres.env


volumes:
  static-content:
  dbdata:
  redis-data:
